// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfshxhseqmynlwbqvuvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mc2h4aHNlcW15bmx3YnF2dXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzY1NjcsImV4cCI6MjA3NDU1MjU2N30.B2QItrtAOQjsuL4PDKyZXfE1q4k6XoAtcOUbR8Qiwwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});